-- MySQL Script generated by MySQL Workbench
-- Fri Mar  3 20:24:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paciente` (
  `idPaciente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `dni` VARCHAR(9) NULL,
  `telefono` VARCHAR(12) NULL,
  `edad` INT NULL,
  `domicilio` VARCHAR(45) NULL,
  `ocupacion` VARCHAR(100) NULL,
  `estado civil` VARCHAR(1) NULL,
  `fecha de inscripcion` DATE NULL,
  PRIMARY KEY (`idPaciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clinica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clinica` (
  `idClinica` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(12) NULL,
  PRIMARY KEY (`idClinica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personal` (
  `idPersonal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `dni` VARCHAR(9) NULL,
  `telefono` VARCHAR(12) NULL,
  `domicilio` VARCHAR(45) NULL,
  `fecha de ingreso` DATE NULL,
  `tiempe_de_sevicio` DATE NULL,
  `estado` VARCHAR(1) NULL,
  PRIMARY KEY (`idPersonal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pago de servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pago de servicio` (
  `idPago de servicio` INT NOT NULL AUTO_INCREMENT,
  `tipo_de_servicio` VARCHAR(45) NULL,
  `presentacion` VARCHAR(45) NULL,
  `precio` DECIMAL(9,2) NULL,
  `codigo_de_pago` VARCHAR(45) NULL,
  `Paciente_idPaciente` INT NOT NULL,
  `Personal_idPersonal` INT NOT NULL,
  PRIMARY KEY (`idPago de servicio`),
  INDEX `fk_Pago de servicio_Paciente1_idx` (`Paciente_idPaciente` ASC),
  INDEX `fk_Pago de servicio_Personal1_idx` (`Personal_idPersonal` ASC),
  CONSTRAINT `fk_Pago de servicio_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `mydb`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pago de servicio_Personal1`
    FOREIGN KEY (`Personal_idPersonal`)
    REFERENCES `mydb`.`Personal` (`idPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reserva de cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reserva de cita` (
  `idreserva de cita` INT NOT NULL AUTO_INCREMENT,
  `numero_de_solicitud` VARCHAR(45) NULL,
  `fecaha` DATE NULL,
  `detalle_de_solicitud` VARCHAR(300) NULL,
  `solicitud de citacol` VARCHAR(45) NULL,
  `Paciente_idPaciente` INT NOT NULL,
  `Clinica_idClinica` INT NOT NULL,
  `Pago de servicio_idPago de servicio` INT NOT NULL,
  PRIMARY KEY (`idreserva de cita`),
  INDEX `fk_solicitud de cita_Paciente_idx` (`Paciente_idPaciente` ASC),
  INDEX `fk_solicitud de cita_Clinica1_idx` (`Clinica_idClinica` ASC),
  INDEX `fk_reserva de cita_Pago de servicio1_idx` (`Pago de servicio_idPago de servicio` ASC),
  CONSTRAINT `fk_solicitud de cita_Paciente`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `mydb`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud de cita_Clinica1`
    FOREIGN KEY (`Clinica_idClinica`)
    REFERENCES `mydb`.`Clinica` (`idClinica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva de cita_Pago de servicio1`
    FOREIGN KEY (`Pago de servicio_idPago de servicio`)
    REFERENCES `mydb`.`Pago de servicio` (`idPago de servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medico especialista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medico especialista` (
  `idmedico especialista` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `dni` VARCHAR(9) NULL,
  `telefono` VARCHAR(12) NULL,
  `edad` INT NULL,
  `especialidad` VARCHAR(45) NULL,
  `numero de paciente` VARCHAR(200) NULL,
  `disponibilidad` VARCHAR(1) NULL,
  PRIMARY KEY (`idmedico especialista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cita` (
  `idCita` INT NOT NULL AUTO_INCREMENT,
  `numerocita` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `estado` VARCHAR(1) NULL,
  `motivo` VARCHAR(45) NULL,
  `turno` VARCHAR(200) NULL,
  `Clinica_idClinica` INT NOT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  `Personal_idPersonal` INT NOT NULL,
  `solicitud de cita_idsolicitud de cita` INT NOT NULL,
  `medico especialista_idmedico especialista` INT NOT NULL,
  PRIMARY KEY (`idCita`),
  INDEX `fk_Cita_Clinica1_idx` (`Clinica_idClinica` ASC),
  INDEX `fk_Cita_Paciente1_idx` (`Paciente_idPaciente` ASC),
  INDEX `fk_Cita_Personal1_idx` (`Personal_idPersonal` ASC),
  INDEX `fk_Cita_solicitud de cita1_idx` (`solicitud de cita_idsolicitud de cita` ASC),
  INDEX `fk_Cita_medico especialista1_idx` (`medico especialista_idmedico especialista` ASC),
  CONSTRAINT `fk_Cita_Clinica1`
    FOREIGN KEY (`Clinica_idClinica`)
    REFERENCES `mydb`.`Clinica` (`idClinica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `mydb`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_Personal1`
    FOREIGN KEY (`Personal_idPersonal`)
    REFERENCES `mydb`.`Personal` (`idPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_solicitud de cita1`
    FOREIGN KEY (`solicitud de cita_idsolicitud de cita`)
    REFERENCES `mydb`.`reserva de cita` (`idreserva de cita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_medico especialista1`
    FOREIGN KEY (`medico especialista_idmedico especialista`)
    REFERENCES `mydb`.`medico especialista` (`idmedico especialista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`calendario de cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`calendario de cita` (
  `idcalendario de cita` INT NOT NULL AUTO_INCREMENT,
  `especialista` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `numero_de_consultorio` VARCHAR(45) NULL,
  `hora` DATE NULL,
  `turno` VARCHAR(200) NULL,
  `medico especialista_idmedico especialista` INT NOT NULL,
  `Personal_idPersonal` INT NOT NULL,
  PRIMARY KEY (`idcalendario de cita`),
  INDEX `fk_calendario de cita_medico especialista1_idx` (`medico especialista_idmedico especialista` ASC),
  INDEX `fk_calendario de cita_Personal1_idx` (`Personal_idPersonal` ASC),
  CONSTRAINT `fk_calendario de cita_medico especialista1`
    FOREIGN KEY (`medico especialista_idmedico especialista`)
    REFERENCES `mydb`.`medico especialista` (`idmedico especialista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calendario de cita_Personal1`
    FOREIGN KEY (`Personal_idPersonal`)
    REFERENCES `mydb`.`Personal` (`idPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`consulta` (
  `idconsulta` INT NOT NULL AUTO_INCREMENT,
  `expediente` VARCHAR(45) NULL,
  `numero_de_consulat` VARCHAR(45) NULL,
  `especilaidad` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `datos_paciente` VARCHAR(45) NULL,
  `consultacol` VARCHAR(45) NULL,
  `medico especialista_idmedico especialista` INT NOT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  `Cita_idCita` INT NOT NULL,
  PRIMARY KEY (`idconsulta`),
  INDEX `fk_consulta_medico especialista1_idx` (`medico especialista_idmedico especialista` ASC),
  INDEX `fk_consulta_Paciente1_idx` (`Paciente_idPaciente` ASC),
  INDEX `fk_consulta_Cita1_idx` (`Cita_idCita` ASC),
  CONSTRAINT `fk_consulta_medico especialista1`
    FOREIGN KEY (`medico especialista_idmedico especialista`)
    REFERENCES `mydb`.`medico especialista` (`idmedico especialista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `mydb`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_Cita1`
    FOREIGN KEY (`Cita_idCita`)
    REFERENCES `mydb`.`Cita` (`idCita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
